# Generated by Django 2.1.3 on 2018-11-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meme',
            new_name='Cheese',
        ),
    ]
